# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40fe5395fe72b55f72c725f7da84bb4d4c838fbc1b5ba5b75b6993f90c49764c8d95bcfe22d54a425ab1eab0e9ca6f5d49a44b9bbf1bd8713d547546e9dec9aa

test:
  secret_key_base: 9823ba2f09c9a0eeaced4cfd9b089845a20583271a286ab9f1befc32f50643b46592b28eaeb3fe83742c98a50affd4d9474af396b0fc207fe0f5ae765d55ae6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
